version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
    directories:
      - /
    cooldown:
      default-days: 7
  - package-ecosystem: nix
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    directories:
      - /
