name: ISO
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/iso.yml
      - flake.nix
      - flake.lock
      - modules/installer.nix
      - modules/hosts/**
      - modules/features/impermanence.nix
      - modules/features/sops.nix
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  detect-hosts:
    name: Detect Hosts
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.detect.outputs.hosts }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/detect-hosts
        id: detect
  build:
    name: Build
    needs: detect-hosts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJSON(needs.detect-hosts.outputs.hosts) }}
    steps:
      - uses: actions/checkout@v6
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: cachix/install-nix-action@v31.10.5
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-iso
          restore-prefixes-all-match: |
            nix-devshell
            nixos-configuration
            nix-iso
          gc-max-store-size-linux: 8G
      - run: nix develop --command nix build .#installer-${{ matrix.host }} --impure
        env:
          NIXPKGS_ALLOW_UNFREE: 1
