name: NixOS Tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - flake.nix
      - flake.lock
      - tests/**
      - modules/features/jellyfin.nix
      - modules/features/telemetry/**
      - .github/workflows/nixos-tests.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        input:
          - jellyfin
          - arr-stack
          - telemetry-host
    steps:
      - uses: actions/checkout@v6
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: cachix/install-nix-action@v31.10.6
        with:
          extra_nix_config: |
            extra-substituters = https://nix-community.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nixos-tests
          restore-prefixes-all-match: |
            nix-devshell
            nixos-tests
          gc-max-store-size-linux: 6G
      - run: nix build .#checks.x86_64-linux.${{ matrix.input }} --impure --print-build-logs
        env:
          NIXPKGS_ALLOW_UNFREE: 1
